<link rel="stylesheet" href="{{ asset('frontend/assets/vendor/line-awesome/line-awesome/line-awesome/css/line-awesome.min.css') }}">
<!-- Plugins CSS File -->
<link rel="stylesheet" href="{{ asset('frontend/assets/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/plugins/owl-carousel/owl.carousel.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/plugins/magnific-popup/magnific-popup.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/plugins/jquery.countdown.css') }}">
<!-- Main CSS File -->
<link rel="stylesheet" href="{{ asset('frontend/assets/css/style.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/skins/site-skin-new.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/site-new.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/toastr.min.css') }}">
<link rel="stylesheet" href="{{ asset('frontend/assets/css/main.css') }}">
